In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
root = os.getcwd()
root

'./fair_taucc'

In [3]:
plot_path = root + "/plots"
plot_path

'./fair_taucc/plots'

In [4]:
dataset = "movielens-1m"
sensitive = "gender"
version = "fair"

# true label dimensions: 
# - cols for movielens, amazon, yelp
# - rows for lfw

In [5]:
taucc_path = root + f"/results/{dataset}/{sensitive}/taucc_{version}/init_random"
frisch_path = root + f"/algorithms/C-Fairness-RecSys/reproducibility_study/Frisch_et_al/results/{dataset}/{sensitive}/lbm_{version}"

In [6]:
taucc = pd.read_csv(taucc_path + "/aggregated.csv")
frisch = pd.read_csv(frisch_path + "/aggregated.csv")

In [7]:
taucc_vanilla_path = root + f"/results/{dataset}/{sensitive}/taucc_vanilla/init_random"
taucc_vanilla = pd.read_csv(taucc_vanilla_path + "/results_aggregated.csv")

frisch_vanilla_path = root + f"/algorithms/C-Fairness-RecSys/reproducibility_study/Frisch_et_al/results/{dataset}/{sensitive}/lbm_baseline"
frisch_vanilla = pd.read_csv(frisch_vanilla_path + "/aggregated.csv")

In [8]:
taucc

,fair_major,fair_minor,tau_x_mean,tau_y_mean,NMI_true_labels_mean,AMI_true_labels_mean,ARI_true_labels_mean,NMI_rows_mean,AMI_rows_mean,ARI_rows_mean,...,NMI_rows_var,AMI_rows_var,ARI_rows_var,NMI_cols_var,AMI_cols_var,ARI_cols_var,balance_chierichetti_var,balance_bera_var,KL_fairness_error_var,time_var
0,0.0,0.0,0.117223,0.115133,0.119846,0.117872,0.107377,0.823447,0.823420,0.873928,...,0.016152,0.016159,0.017901,0.007643,0.007649,0.006172,5.559300e-04,0.002652,7.883202e-05,1007.259130
1,0.0,0.1,0.118573,0.117591,0.118934,0.117084,0.106330,0.851141,0.851121,0.903439,...,0.010250,0.010255,0.011266,0.004439,0.004442,0.002869,5.857572e-05,0.000262,4.221119e-06,450.535234
2,0.0,0.2,0.111028,0.108829,0.117275,0.115053,0.093196,0.685005,0.684952,0.720187,...,0.063727,0.063753,0.078866,0.041705,0.041733,0.046924,7.258013e-04,0.003650,1.264694e-04,667.420299
3,0.0,0.3,0.117303,0.115234,0.114707,0.112715,0.103359,0.840402,0.840376,0.883571,...,0.020633,0.020641,0.021855,0.010717,0.010725,0.007109,4.252072e-04,0.002036,6.457143e-05,876.244805
4,0.0,0.4,0.112421,0.111448,0.121024,0.118955,0.098179,0.752544,0.752502,0.785866,...,0.061984,0.062008,0.072436,0.046974,0.047005,0.055534,1.118219e-03,0.005820,3.757474e-04,700.424912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,1.0,0.6,0.098336,0.099441,0.118727,0.116613,0.105999,0.567669,0.567600,0.621907,...,0.050733,0.050755,0.062144,0.026566,0.026581,0.022667,1.940769e-03,0.008809,6.751974e-04,34146.235952
117,1.0,0.7,0.106991,0.105056,0.112522,0.110521,0.100468,0.683600,0.683557,0.752718,...,0.004841,0.004844,0.007199,0.006403,0.006409,0.004845,4.588145e-04,0.001939,2.928952e-05,3806.363392
118,1.0,0.8,0.090258,0.102550,0.118275,0.116199,0.100320,0.542959,0.542873,0.563583,...,0.036987,0.037010,0.063429,0.031118,0.031140,0.036986,1.497374e-04,0.002818,1.324896e-04,17904.026055
119,1.0,0.9,0.066038,0.087720,0.110980,0.108496,0.089863,0.380173,0.380024,0.361879,...,0.032562,0.032585,0.057353,0.030905,0.030928,0.034361,3.081778e-07,0.006355,3.029491e-04,32644.274811
120,1.0,1.0,0.021163,0.087773,0.092784,0.089955,0.069511,0.242199,0.241821,0.115419,...,0.003013,0.003016,0.000576,0.013408,0.013419,0.019072,2.273213e-07,0.000009,1.274921e-09,9294.851772

In [9]:
fair_taucc = taucc[(taucc["fair_major"]==1.0) & (taucc["fair_minor"]==1.0)]
#fair_taucc = taucc[(taucc["fair_major"]==1.0) & (taucc["fair_minor1"]==1.0) & (taucc["fair_minor2"]==1.0)]
fair_taucc

,fair_major,fair_minor,tau_x_mean,tau_y_mean,NMI_true_labels_mean,AMI_true_labels_mean,ARI_true_labels_mean,NMI_rows_mean,AMI_rows_mean,ARI_rows_mean,...,NMI_rows_var,AMI_rows_var,ARI_rows_var,NMI_cols_var,AMI_cols_var,ARI_cols_var,balance_chierichetti_var,balance_bera_var,KL_fairness_error_var,time_var
120,1.0,1.0,0.021163,0.087773,0.092784,0.089955,0.069511,0.242199,0.241821,0.115419,...,0.003013,0.003016,0.000576,0.013408,0.013419,0.019072,2.273213e-07,0.000009,1.274921e-09,9294.851772

In [10]:
mask_col1 = taucc['fair_major'].isin([0.9, 1.0])
mask_col2 = taucc['fair_minor'].isin([0.9, 1.0])
mask_different = taucc["fair_major"] != taucc["fair_minor"]
taucc_relax = taucc[mask_col1 & mask_col2 & mask_different]
taucc_relax
#mask_col2 = taucc['fair_minor1'].isin([0.9, 1.0])
#mask_col3 = taucc['fair_minor2'].isin([0.9, 1.0])
#taucc_relax = taucc[mask_col1 & mask_col2 & mask_col3]
#taucc_relax

,fair_major,fair_minor,tau_x_mean,tau_y_mean,NMI_true_labels_mean,AMI_true_labels_mean,ARI_true_labels_mean,NMI_rows_mean,AMI_rows_mean,ARI_rows_mean,...,NMI_rows_var,AMI_rows_var,ARI_rows_var,NMI_cols_var,AMI_cols_var,ARI_cols_var,balance_chierichetti_var,balance_bera_var,KL_fairness_error_var,time_var
109,0.9,1.0,0.095866,0.099097,0.10408,0.101693,0.080465,0.507592,0.507503,0.542048,...,0.057331,0.057359,0.077119,0.031716,0.031739,0.036498,1.557279e-04,0.000313,0.000002,24977.609873
119,1.0,0.9,0.066038,0.087720,0.11098,0.108496,0.089863,0.380173,0.380024,0.361879,...,0.032562,0.032585,0.057353,0.030905,0.030928,0.034361,3.081778e-07,0.006355,0.000303,32644.274811

In [11]:
index_max = taucc_relax['tau_x_mean'].idxmax()
row_max = taucc_relax.loc[index_max]
taucc_relax = pd.DataFrame([row_max])
taucc_relax

,fair_major,fair_minor,tau_x_mean,tau_y_mean,NMI_true_labels_mean,AMI_true_labels_mean,ARI_true_labels_mean,NMI_rows_mean,AMI_rows_mean,ARI_rows_mean,...,NMI_rows_var,AMI_rows_var,ARI_rows_var,NMI_cols_var,AMI_cols_var,ARI_cols_var,balance_chierichetti_var,balance_bera_var,KL_fairness_error_var,time_var
109,0.9,1.0,0.095866,0.099097,0.10408,0.101693,0.080465,0.507592,0.507503,0.542048,...,0.057331,0.057359,0.077119,0.031716,0.031739,0.036498,0.000156,0.000313,0.000002,24977.609873

In [12]:
taucc_vanilla = taucc_vanilla.rename(columns={
    'ARI_mean':'ARI_true_labels_mean', 
    'ARI_std': 'ARI_true_labels_std',
    'ARI_var': 'ARI_true_labels_var',
    'AMI_mean':'AMI_true_labels_mean', 
    'AMI_std': 'AMI_true_labels_std',
    'AMI_var': 'AMI_true_labels_var',
    'NMI_mean':'NMI_true_labels_mean', 
    'NMI_std': 'NMI_true_labels_std',
    'NMI_var': 'NMI_true_labels_var',
})

In [13]:
df = pd.concat([taucc_vanilla, fair_taucc, taucc_relax, frisch_vanilla, frisch], ignore_index=True)
df

,tau_x_mean,tau_x_std,tau_x_var,tau_y_mean,tau_y_std,tau_y_var,NMI_true_labels_mean,NMI_true_labels_std,NMI_true_labels_var,AMI_true_labels_mean,...,ARI_cols_std,NMI_rows_var,AMI_rows_var,ARI_rows_var,NMI_cols_var,AMI_cols_var,ARI_cols_var,NLL_mean,NLL_std,NLL_var
0,0.113785,0.008894,0.000079,0.110683,0.012225,0.000149,0.115085,0.011243,0.000126,0.112922,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.021163,0.004167,0.000017,0.087773,0.008865,0.000079,0.092784,0.011759,0.000138,0.089955,...,0.138100,0.003013,0.003016,0.000576,0.013408,0.013419,0.019072,NaN,NaN,NaN
2,0.095866,0.021521,0.000463,0.099097,0.015234,0.000232,0.104080,0.009627,0.000093,0.101693,...,0.191044,0.057331,0.057359,0.077119,0.031716,0.031739,0.036498,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,0.090642,0.006017,0.000036,0.070023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.986388e+06,1220.296004,1.489122e+06
4,NaN,NaN,NaN,NaN,NaN,NaN,0.091569,0.005204,0.000027,0.070992,...,0.034713,0.000319,0.000330,0.000500,0.000324,0.000341,0.001205,3.985210e+06,918.508167,8.436573e+05

In [15]:
df.insert(0, "algorithm", ["TauCC", "Fair TauCC", "Fair TauCC v2", "LBM", "Parity LBM"])
df

,algorithm,tau_x_mean,tau_x_std,tau_x_var,tau_y_mean,tau_y_std,tau_y_var,NMI_true_labels_mean,NMI_true_labels_std,NMI_true_labels_var,...,ARI_cols_std,NMI_rows_var,AMI_rows_var,ARI_rows_var,NMI_cols_var,AMI_cols_var,ARI_cols_var,NLL_mean,NLL_std,NLL_var
0,TauCC,0.113785,0.008894,0.000079,0.110683,0.012225,0.000149,0.115085,0.011243,0.000126,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fair TauCC,0.021163,0.004167,0.000017,0.087773,0.008865,0.000079,0.092784,0.011759,0.000138,...,0.138100,0.003013,0.003016,0.000576,0.013408,0.013419,0.019072,NaN,NaN,NaN
2,Fair TauCC v2,0.095866,0.021521,0.000463,0.099097,0.015234,0.000232,0.104080,0.009627,0.000093,...,0.191044,0.057331,0.057359,0.077119,0.031716,0.031739,0.036498,NaN,NaN,NaN
3,LBM,NaN,NaN,NaN,NaN,NaN,NaN,0.090642,0.006017,0.000036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.986388e+06,1220.296004,1.489122e+06
4,Parity LBM,NaN,NaN,NaN,NaN,NaN,NaN,0.091569,0.005204,0.000027,...,0.034713,0.000319,0.000330,0.000500,0.000324,0.000341,0.001205,3.985210e+06,918.508167,8.436573e+05

In [16]:
df[["algorithm", "tau_x_mean", "tau_x_std", "tau_y_mean", "tau_y_std", "ARI_true_labels_mean", "ARI_true_labels_std", "ARI_rows_mean", "ARI_rows_std", "ARI_cols_mean", "ARI_cols_std", "balance_bera_mean", "balance_bera_std", "KL_fairness_error_mean", "KL_fairness_error_std", "time_mean", "time_std"]]

,algorithm,tau_x_mean,tau_x_std,tau_y_mean,tau_y_std,ARI_true_labels_mean,ARI_true_labels_std,ARI_rows_mean,ARI_rows_std,ARI_cols_mean,ARI_cols_std,balance_bera_mean,balance_bera_std,KL_fairness_error_mean,KL_fairness_error_std,time_mean,time_std
0,TauCC,0.113785,0.008894,0.110683,0.012225,0.099032,0.016710,NaN,NaN,NaN,NaN,0.786248,0.053321,0.019257,0.009754,3.617867,1.277285
1,Fair TauCC,0.021163,0.004167,0.087773,0.008865,0.069511,0.022022,0.115419,0.024010,0.594588,0.138100,0.969186,0.002930,0.000223,0.000036,490.036343,96.409812
2,Fair TauCC v2,0.095866,0.021521,0.099097,0.015234,0.080465,0.025968,0.542048,0.277703,0.717184,0.191044,0.918666,0.017678,0.002661,0.001298,217.847115,158.043063
3,LBM,NaN,NaN,NaN,NaN,0.024730,0.003044,NaN,NaN,NaN,NaN,0.535317,0.151921,0.391824,0.167760,5110.044662,248.721871
4,Parity LBM,NaN,NaN,NaN,NaN,0.025731,0.003565,0.255674,0.022355,0.510051,0.034713,0.600474,0.087154,0.169335,0.025705,5262.004506,257.769488

## Fairness

In [ ]:
algo = df["algorithm"]
metrics_labels = ["balance_bera", "balance_chierichetti", "KL_fairness_error"]

metrics = {
    "Fair TauCC": [],
    "Parity LBM": []
}

metrics_std = {
    "Fair TauCC": [],
    "Parity LBM": []
}

for label in metrics_labels:
    
    metrics["Fair TauCC"].append(
        np.round(taucc[label+"_mean"].values[0], 2)
    )
    metrics_std["Fair TauCC"].append(
        np.round(taucc[label+"_std"].values[0], 2)
    )
    
    metrics["Parity LBM"].append(
        np.round(frisch[label+"_mean"].values[0], 2)
    )
    metrics_std["Parity LBM"].append(
        np.round(frisch[label+"_std"].values[0], 2)
    )
    
print(metrics)

x = np.arange(len(metrics_labels))  # the label locations
width = 0.20  # the width of the bars
multiplier = -0.5

fig, ax = plt.subplots(layout='constrained')

for attribute, measurement in metrics.items():
    offset = width * multiplier
    errors = metrics_std[attribute]
    #rects = ax.bar(x + offset, measurement, width, label=attribute, yerr=errors, capsize=5)
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3)
    multiplier += 1

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_title('Results on Fairness')
ax.set_xticks(x + width, metrics_labels)
ax.legend(loc='upper right')

#plt.show()
plt.savefig(plot_path + f"/{dataset}_{sensitive}_fairness.png")

## NMI, AMI, ARI w.r.t. true labels

In [ ]:
algo = df["algorithm"]
metrics_labels = ["NMI_true_labels", "ARI_true_labels", "AMI_true_labels"]
    

metrics = {
    "Fair TauCC": [],
    "Parity LBM": [],
}

metrics_std = {
    "Fair TauCC": [],
    "Parity LBM": [],
}

for label in metrics_labels:
    
    metrics["Fair TauCC"].append(
        np.round(taucc[label+"_mean"].values[0], 2)
    )
    metrics_std["Fair TauCC"].append(
        np.round(taucc[label+"_std"].values[0], 2)
    )
    
    metrics["Parity LBM"].append(
        np.round(frisch[label+"_mean"].values[0], 2)
    )
    metrics_std["Parity LBM"].append(
        np.round(frisch[label+"_std"].values[0], 2)
    )

print(metrics)

x = np.arange(len(metrics_labels))  # the label locations

if dataset == "lfw":
    width = 0.20  # the width of the bars
    multiplier = -0.5
else:
    width = 0.25  # the width of the bars
    multiplier = 0.5

fig, ax = plt.subplots(layout='constrained')

for attribute, measurement in metrics.items():
    offset = width * multiplier
    errors = metrics_std[attribute]
    #rects = ax.bar(x + offset, measurement, width, label=attribute, yerr=errors, capsize=5)
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3)
    multiplier += 1

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_title('Results on clustering quality (fair vs true labels)')
ax.set_xticks(x + width, metrics_labels)
ax.legend(loc='upper center')

#plt.show()
plt.savefig(plot_path + f"/{dataset}_{sensitive}_true_labels.png")

## NMI, ARI, AMI w.r.t. vanilla rows

In [ ]:
algo = df["algorithm"]
metrics_labels = ["NMI_rows", "ARI_rows", "AMI_rows"]

metrics = {
    "Fair TauCC": [],
    "Parity LBM": []
}

metrics_std = {
    "Fair TauCC": [],
    "Parity LBM": []
}

for label in metrics_labels:
    
    metrics["Fair TauCC"].append(
        np.round(taucc[label+"_mean"].values[0], 2)
    )
    metrics_std["Fair TauCC"].append(
        np.round(taucc[label+"_std"].values[0], 2)
    )
    
    metrics["Parity LBM"].append(
        np.round(frisch[label+"_mean"].values[0], 2)
    )
    metrics_std["Parity LBM"].append(
        np.round(frisch[label+"_std"].values[0], 2)
    )
    

print(metrics)

x = np.arange(len(metrics_labels))  # the label locations
width = 0.20  # the width of the bars
multiplier = -0.5

fig, ax = plt.subplots(layout='constrained')

for attribute, measurement in metrics.items():
    offset = width * multiplier
    errors = metrics_std[attribute]
    #rects = ax.bar(x + offset, measurement, width, label=attribute, yerr=errors, capsize=5)
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3)
    multiplier += 1

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_title('Results on Co-clustering quality (fair vs vanilla on rows)')
ax.set_xticks(x + width, metrics_labels)
ax.legend(loc='upper center')

#plt.show()
plt.savefig(plot_path + f"/{dataset}_{sensitive}_rows.png")

## NMI, ARI, AMI w.r.t. vanilla cols

In [ ]:
# Dati esemplificativi
algo = df["algorithm"]
metrics_labels = ["NMI_cols", "ARI_cols", "AMI_cols"]

metrics = {
    "Fair TauCC": [],
    "Parity LBM": []
}

metrics_std = {
    "Fair TauCC": [],
    "Parity LBM": []
}

for label in metrics_labels:
    
    metrics["Fair TauCC"].append(
        np.round(taucc[label+"_mean"].values[0], 2)
    )
    metrics_std["Fair TauCC"].append(
        np.round(taucc[label+"_std"].values[0], 2)
    )
    
    metrics["Parity LBM"].append(
        np.round(frisch[label+"_mean"].values[0], 2)
    )
    metrics_std["Parity LBM"].append(
        np.round(frisch[label+"_std"].values[0], 2)
    )
    

print(metrics)

x = np.arange(len(metrics_labels))  # the label locations
width = 0.25  # the width of the bars
multiplier = 0.5

fig, ax = plt.subplots(layout='constrained')

for attribute, measurement in metrics.items():
    offset = width * multiplier
    errors = metrics_std[attribute]
    #rects = ax.bar(x + offset, measurement, width, label=attribute, yerr=errors, capsize=5)
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3)
    multiplier += 1

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_title('Results on clustering quality (fair vs vanilla on columns)')
ax.set_xticks(x + width, metrics_labels)
ax.legend(loc='upper right')

#plt.show()
plt.savefig(plot_path + f"/{dataset}_{sensitive}_cols.png")